version: '3.8'
services:

  ewm-service:
    restart: on-failure
    build: ./main-service
    image: ewm-main-service
    container_name: "ewm-main-service"
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main_db
        - POSTGRES_USER=owner
        - POSTGRES_PASSWORD=password
        - DB_NAME=main_db
        - SPRING_DATASOURCE_USERNAME=owner
        - SPRING_DATASOURCE_PASSWORD=password
        - DB_HOST=main-db
        - DB_PORT=6542

  main-db:
    image: postgres:14-alpine
    container_name: "main-db"
    ports:
      - "6542:5432"
    volumes:
      - /var/lib/postgresql/main-service
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=password